### ISSUE TITLE
No MSTestX.TestRunnerActivity exists in v1.2.1 (existed in 1.1.2)

### ISSUE THREAD

**Issue by natashavg** [dotMorten/MSTestX#12] opened 2020-09-14 17:40 UTC
Hello,

I tried following your readme and it does not recognize TestRunnerActivity inside MSTestX.

1. I added Mobile App Project (Xamarin.Forms) inside my solution. 
2. Updated Xamarin.Forms in nuget package manager (adding MSTestX.UnitTestRunner fails if not done). 
3. Deleted the .axml files inside the main project that was created. 
4. Also, added reference to MSTestX.UnitTestRunner.
5. Now when I edit MainActivity in MyRunnerProject.Android, it is okay with MSTestX part, but says there is no TestRunnerActivity inside MSTestX. 

Intellisense gives me these inside MSTestX:
*RunnerApp
*TestOptions
*Styles
*UnitTestRunner

What could I be doing wrong?

**Why I want to use MSTestX**
I have an old test project I created to test a class project in a solution with multiple devs. One of the devs merged the class project into the main android xamarin project, and now my old test project tests are failing because it is saying it cannot load the classes from the android project for some reason. I thought MSTestX could fix the reason it is failing. (I have a project called MainApp and a project called TestProject. I used to have a project called Class. TestProject runs test against Class. Class was moved into MainApp.)

**The error I get in my old Test project, that resulted in me wanting to try MSTestX:**
"Message: Test method SolutionName.TestProject.ClassTester.NameOfTest threw exception: 
System.TypeLoadException: Could not load type 'SolutionName.MainProject.Class' from assembly 'SolutionName, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'."

**Update:** In the comments below it shows that I got it running. Basically maybe some differences in the way VS2017 was scaffolding Android/Forms projects, but the problem with MSTestX.TestRunnerActivity not existing is still an issue in MSTestX 1.2.1. I reverted to 1.1.2 in order to be able to use MSTestX

**Comment by natashavg** [comment] 2020-09-14 17:51
Update: If I downgrade MSTestX.UnitTestRunner to 1.0.1 (from newest 1.2.1), then TestRunnerActivity is found, but the default code inside MainActivity fails due to the line `LoadApplication(new App());` because of error: `Error	CS0246	The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)	MSTestRunner.Android	23	Active`

**Comment by dotMorten** [comment] 2020-09-14 17:52
Which version of Xamarin.Forms are you targeting?

**Comment by dotMorten** [comment] 2020-09-14 17:54
Oh wait are you trying to reference an app project? Your tests should be in a class library or in the test app project itself

**Comment by natashavg** [comment] 2020-09-14 17:56
So, I have a solution that has (1) an Android project, (2) a Test project (class library), (3) new MSTestX project

The Test project is testing classes inside of the Android project

The MSTestX project I am trying to create is targeting Xamarin.Forms 4.8.0.1364

**Comment by dotMorten** [comment] 2020-09-14 17:57
Perhaps you could provide a small sample that reproduces the issue? Lots of guessing at my end here. Easier if I can just run it and see for myself

**Comment by natashavg** [comment] 2020-09-14 18:02
So at the moment, it is failing at a very basic level, without me even referencing or adding references to my Android project to the MSTestX project. Just following the steps in your ReadMe, adding the TestRunnerActivity to the MainActivity file says that MSTestX does not contain TestRunnerActivity, unless I go to an older version of MSTestX.UnitTestRunner.

I'll try to upload a file showing this

**Comment by natashavg** [comment] 2020-09-14 18:37
Here is a basic VS Solution File with a blank Test (for MSTest Asserts), a blank Android project, and a failing MSTestX Forms project.

https://github.com/natashavg/ExampleMSTestX

**Edit:** Look at the initial commit version to get the error, as the example has since been fixed to use an older version of MSTestX in order to run

**Comment by natashavg** [comment] 2020-09-14 18:46
MSTestX.UnitTestRunner 1.1.2 is the last version that allows me to use MSTestX.TestRunnerActivity

Edit: I commited the downgrade to 1.1.2 to the git repo, so to see the failure you have to use the old commit.
Edit: I also commited the change from `LoadApplication(new App());` to `LoadApplication(new Xamarin.Forms.Application());` in MainActivity.cs in order to clear all errors.

**Comment by natashavg** [comment] 2020-09-14 19:25
Also, should I be right clicking on the Android project created for MSTestX (mine is named TestX.Android), and selecting Set as Startup Project, and then running it? I get a `System.NullReferenceException: Object reference not set to an instance of an object.`

It has `No compatible code running`, so doesn't show the breakpoint for this error.

**Comment by natashavg** [comment] 2020-09-14 21:20
To fix the null reference exception, I just commented out all of the code inside the MainActivity : MSTestX.TestRunnerActivity, except the base.OnCreate function:

```
    public class MainActivity : MSTestX.TestRunnerActivity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            //TabLayoutResource = Resource.Layout.Tabbar;
            //ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);
            //global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            //LoadApplication(new Xamarin.Forms.Application());
        }
    }
```

**Comment by dotMorten** [comment] 2023-11-06 23:18
Closing since Xamarin support is deprecated/removed.

**Closed as completed by dotMorten** 2023-11-06 23:18 UTC
